# Generated by Django 5.2.4 on 2025-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemdesignsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='systemdesignsubmission',
            name='design_image',
            field=models.ImageField(blank=True, help_text='Uploaded design image', null=True, upload_to='design_submissions/'),
        ),
        migrations.AlterField(
            model_name='systemdesignsubmission',
            name='design_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
