# Generated by Django 5.2.4 on 2025-08-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_design', '0002_alter_systemdesignsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemdesignsubmission',
            name='design_data',
        ),
    ]
