# Generated by Django 5.2.4 on 2025-09-07 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_design', '0003_remove_systemdesignsubmission_design_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdesignsubmission',
            name='design_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Uploaded design image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
