services:
  web:
    build: 736744502587.dkr.ecr.eu-north-1.amazonaws.com/my-django-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=src.settings
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - GOOGLE_OAUTH2_SECRET=${GOOGLE_OAUTH2_SECRET}
      - GOOGLE_OAUTH2_KEY=${GOOGLE_OAUTH2_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - PYTHONPATH=/app/src
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app/src
    depends_on:
      db: 
        condition: service_healthy
        restart: true
  db:
    image: pgvector/pgvector:pg17-trixie
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    env_file:
      - .env

volumes:
  postgres_db: