# Generated by Django 5.2.4 on 2025-08-25 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(default='avatars/default.webp', upload_to='avatars/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interests', models.TextField(blank=True, help_text='Your interests (comma-separated): machine learning, web development, data science', max_length=300)),
                ('skills', models.TextField(blank=True, help_text='Technical skills (comma-separated): Python, React, Docker', max_length=200)),
                ('role', models.CharField(blank=True, help_text='Your role: Frontend Developer, Data Scientist, etc.', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
