# Generated by Django 5.2.4 on 2025-08-26 15:38

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='profile',
            name='embeddings',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
