# Generated by Django 5.2.4 on 2025-07-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, help_text='Your interests (comma-separated): machine learning, web development, data science', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, help_text='Your role: Frontend Developer, Data Scientist, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Technical skills (comma-separated): Python, React, Docker', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.webp', upload_to='avatars/'),
        ),
    ]
