# Generated by Django 5.2.4 on 2025-09-07 15:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_embeddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default.webp', max_length=255, verbose_name='image'),
        ),
    ]
