# Generated by Django 5.2.4 on 2025-07-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_prep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartprepsession',
            name='user',
        ),
    ]
