# Generated by Django 5.2.4 on 2025-08-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_embeddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the blog post', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='target_role',
            field=models.CharField(blank=True, help_text='Target roles (comma-separated): Software Engineer, Data Scientist', max_length=200),
        ),
    ]
